### ISSUE TITLE
File is missing.

### ISSUE THREAD

**Issue by malwaremanu** [dev-rohit0/tailwind-whatsapp-clone#1]
https://github.com/dev-rohit0/tailwind-whatsapp-clone/blob/05cfc6ad6daae24fd42684da6bddd322453f8b88/index.html#L24

**Comment by dev-rohit0** [comment]
These images are my personal images so I removed them. You can use any image just keep in mind to put the image in the following directory `/images/dp.jpg` . I hope this will resolve the issue.
